services:
  api:
    build:
      context: ./api
    container_name: api
    networks:
      - local-net
    ports:
      - "3000:3000"

  runner:
    build:
      context: ./runner
    container_name: runner
    networks:
      - local-net
    environment:
      API_HOST: api
      API_PORT: 3000
    entrypoint: ["python", "main.py"]

networks:
  local-net:
    name: local-net
